from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ContextTypes, MessageHandler, filters
from src.middleware import restricted
from src.utils import generate_case_id
from src.integrations.notion_client import DelegadoNotionClient
from src.integrations.drive_client import DelegadoDriveClient
from src.integrations.docs_client import DelegadoDocsClient
from src.session_manager import session_manager, SessionState
from src.agents.orchestrator import agent_orchestrator
from datetime import datetime

# Initialize clients
notion = DelegadoNotionClient()
drive = DelegadoDriveClient()
docs = DelegadoDocsClient()

@restricted
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handler for the /start command. Handles Deep Linking."""
    user_id = update.effective_user.id
    args = context.args

    # Check for Deep Linking (e.g., /start case_D-2026-001)
    if args and args[0].startswith("case_"):
        case_id = args[0].replace("case_", "")
        session_manager.set_active_case(user_id, case_id)
        
        await update.message.reply_text(
            f"🎯 *MODO EDICIÓN ACTIVO*\n"
            f"Te has vinculado al expediente `{case_id}`.\n\n"
            "Todo lo que envíes aquí (texto, fotos, audios) se procesará para este caso.\n"
            "Usa /stop para salir del modo edición.",
            parse_mode='Markdown'
        )
        return

    await update.message.reply_text(
        "👋 Hola, Delegado.\n\n"
        "Soy tu asistente jurídico-administrativo 'Delegado 360'.\n"
        "Estoy listo para gestionar expedientes.\n\n"
        "Comandos disponibles:\n"
        "/denuncia [hechos] - Iniciar denuncia ITSS\n"
        "/demanda [tipo] - Iniciar demanda judicial\n"
        "/email [asunto] - Redactar email a RRHH"
    )

@restricted
async def denuncia_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handler for the /denuncia command."""
    context_args = " ".join(context.args)
    if not context_args:
        await update.message.reply_text("⚠️ Por favor, describe los hechos para iniciar la denuncia.\nEjemplo: /denuncia Falta de EPIs en el almacén")
        return

    # 1. Generate ID
    case_id = generate_case_id("D")
    user = update.effective_user.first_name
    
    await update.message.reply_text(f"🔄 Procesando expediente {case_id}...")

    # 2. Notion Entry
    notion_page_id = notion.create_case_page({
        "id": case_id,
        "type": "Denuncia ITSS",
        "status": "Borrador",
        "company": "Detectar o Pendiente",
        "created_at": datetime.now(),
        "initial_context": context_args
    })

    # 3. Drive Folder
    drive_link, folder_id = None, None
    if drive.service:
        drive_link, folder_id = drive.create_case_folder(case_id, context_args[:30])
        if folder_id:
            drive.create_subfolder(folder_id, "Pruebas")
            drive.create_subfolder(folder_id, "Respuestas")

    # 4. Google Doc (Generated by Agent)
    doc_link = None
    if folder_id and docs.service:
        agent = agent_orchestrator.get_agent_for_command("/denuncia")
        draft_content = agent.generate_draft(context_args)
        doc_link = docs.create_draft_document(f"{case_id} - Borrador", draft_content, folder_id)

    # 5. Update Notion links
    if notion_page_id and (drive_link or doc_link):
        notion.update_page_links(notion_page_id, drive_link, doc_link)

    # 6. Final Response with Button
    response = f"✅ *EXPEDIENTE CREADO*\n\n📋 *ID:* `{case_id}`\n📂 *Tipo:* Denuncia ITSS\n👤 *Responsable:* {user}\n\n"
    
    if notion_page_id: response += f"🔗 [Ver en Notion](https://notion.so/{notion_page_id.replace('-', '')})\n"
    if drive_link: response += f"📁 [Carpeta Drive]({drive_link})\n"
    if doc_link: response += f"📄 [Borrador Doc]({doc_link})\n"

    # Deep Link Button
    bot_username = context.bot.username
    deep_link = f"https://t.me/{bot_username}?start=case_{case_id}"
    keyboard = [[InlineKeyboardButton("🔒 Continuar en Privado", url=deep_link)]]
    reply_markup = InlineKeyboardMarkup(keyboard)

    await update.message.reply_text(response, parse_mode='Markdown', reply_markup=reply_markup)

@restricted
async def status_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handler for /status command. Updates Notion status."""
    args = context.args
    if len(args) < 2:
        await update.message.reply_text("⚠️ Uso: /status [ID_CASO] [NUEVO_ESTADO]\nEjemplo: /status D-2026-001 Enviado")
        return

    case_id = args[0]
    new_status = " ".join(args[1:])

    await update.message.reply_text(f"🔄 Actualizando {case_id} a '{new_status}'...")
    
    if notion.client:
        success = notion.update_case_status(case_id, new_status)
        if success:
            await update.message.reply_text(f"✅ Estado actualizado correctamente en Notion.")
        else:
            await update.message.reply_text(f"❌ Error actualizando Notion (¿El caso existe?).")
    else:
        await update.message.reply_text(f"⚠️ [Simulado] Estado actualizado a '{new_status}' (Notion no conectado).")

@restricted
async def private_message_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handles messages in private chat based on session state."""
    user_id = update.effective_user.id
    session = session_manager.get_session(user_id)
    
    if session["state"] != SessionState.EDITING_CASE:
        return # Ignore normal messages or handle as generic

    case_id = session["active_case_id"]
    
    # Handle Files
    if update.message.document or update.message.photo or update.message.voice:
        # Here we would implement file download and upload to Drive
        # For now, simulated response
        file_type = "Archivo"
        if update.message.photo: file_type = "Foto"
        elif update.message.voice: file_type = "Audio"
        
        await update.message.reply_text(f"📎 {file_type} recibido. Subiendo a carpeta del caso `{case_id}`... (Simulado)")
        return

    # Handle Text (Refinement)
    text = update.message.text
    await update.message.reply_text(f"📝 Texto recibido para caso `{case_id}`. Analizando para actualizar borrador... (Simulado)")

@restricted
async def stop_editing_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Exits editing mode."""
    user_id = update.effective_user.id
    session_manager.clear_session(user_id)
    await update.message.reply_text("⏹️ Has salido del modo edición.")

@restricted
async def demanda_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handler for the /demanda command."""
    context_args = " ".join(context.args)
    if not context_args:
        await update.message.reply_text("⚠️ Por favor, especifica el tipo y hechos.\nEjemplo: /demanda despido Despido improcedente de Juan")
        return

    await update.message.reply_text(f"⚖️ [Simulación] Iniciando expediente de DEMANDA con contexto: '{context_args}'")

@restricted
async def email_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handler for the /email command."""
    context_args = " ".join(context.args)
    if not context_args:
        await update.message.reply_text("⚠️ Por favor, indica el asunto y el mensaje.\nEjemplo: /email Solicitud Vacaciones Pedir el calendario anual")
        return

    await update.message.reply_text(f"📧 [Simulación] Redactando EMAIL con contexto: '{context_args}'")
